"""AIOS — Artificial Intelligence Operating System (blueprint Volume 12).

Provides a common kernel that modules can boot onto, replacing duplicated
infrastructure with shared lifecycle, health, metrics, security, scheduling,
monitoring and logging primitives. Reuses the Vol 10 integration bus/logger
for events and audit trails.
"""
from __future__ import annotations

from modules.aios.kernel import (
    KERNEL_NAME,
    KERNEL_VERSION,
    Kernel,
    KernelAPI,
    KernelHealth,
    KernelLogger,
    KernelManager,
    KernelMetrics,
    KernelMonitor,
    KernelPermissionDeniedError,
    KernelRuntime,
    KernelScheduler,
    KernelSecurity,
    get_kernel,
    get_kernel_api,
    get_kernel_health,
    get_kernel_logger,
    get_kernel_manager,
    get_kernel_metrics,
    get_kernel_monitor,
    get_kernel_runtime,
    get_kernel_scheduler,
    get_kernel_security,
    version_info,
)
from modules.aios.runtime import (
    RuntimeCleanup,
    RuntimeContext,
    RuntimeEngine,
    RuntimeExecutor,
    RuntimeMetrics,
    RuntimeSession,
    RuntimeState,
    get_runtime_cleanup,
    get_runtime_engine,
    get_runtime_executor,
    get_runtime_metrics,
)
from modules.aios.sandbox import (
    NetworkAccess,
    Sandbox,
    SandboxLimitError,
    SandboxLimits,
    SandboxManager,
    SandboxNetwork,
    SandboxPermissionDeniedError,
    SandboxPermissions,
    SandboxPolicy,
    SandboxStorage,
    get_sandbox_manager,
    restrictive_policy,
)

__all__ = [
    "KERNEL_NAME",
    "KERNEL_VERSION",
    "Kernel",
    "KernelAPI",
    "KernelHealth",
    "KernelLogger",
    "KernelManager",
    "KernelMetrics",
    "KernelMonitor",
    "KernelPermissionDeniedError",
    "KernelRuntime",
    "KernelScheduler",
    "KernelSecurity",
    "get_kernel",
    "get_kernel_api",
    "get_kernel_health",
    "get_kernel_logger",
    "get_kernel_manager",
    "get_kernel_metrics",
    "get_kernel_monitor",
    "get_kernel_runtime",
    "get_kernel_scheduler",
    "get_kernel_security",
    "version_info",
    "RuntimeCleanup",
    "RuntimeContext",
    "RuntimeEngine",
    "RuntimeExecutor",
    "RuntimeMetrics",
    "RuntimeSession",
    "RuntimeState",
    "get_runtime_cleanup",
    "get_runtime_engine",
    "get_runtime_executor",
    "get_runtime_metrics",
    "NetworkAccess",
    "Sandbox",
    "SandboxLimitError",
    "SandboxLimits",
    "SandboxManager",
    "SandboxNetwork",
    "SandboxPermissionDeniedError",
    "SandboxPermissions",
    "SandboxPolicy",
    "SandboxStorage",
    "get_sandbox_manager",
    "restrictive_policy",
]
