"""BI Interfaces — Abstract interfaces for BI components."""
from typing import Any, Dict, List, Protocol


class IDataSource(Protocol):
    def connect(self) -> bool: ...
    def disconnect(self) -> None: ...
    def query(self, sql: str) -> List[Dict[str, Any]]: ...
    def get_schema(self) -> Dict[str, str]: ...


class IAnalyzer(Protocol):
    def analyze(self, data: List[Dict[str, Any]], analysis_type: str) -> Dict[str, Any]: ...
    def get_insights(self) -> List[Dict[str, Any]]: ...


class IPredictor(Protocol):
    def train(self, data: List[Dict[str, Any]], target: str) -> bool: ...
    def predict(self, features: Dict[str, Any]) -> float: ...
    def get_accuracy(self) -> float: ...


class IDashboard(Protocol):
    def add_widget(self, widget: Dict[str, Any]) -> str: ...
    def remove_widget(self, widget_id: str) -> bool: ...
    def render(self) -> Dict[str, Any]: ...


class IReporter(Protocol):
    def generate(self, config: Dict[str, Any]) -> str: ...
    def export(self, format: str) -> bytes: ...


class IDecisionEngine(Protocol):
    def evaluate(self, context: Dict[str, Any]) -> Dict[str, Any]: ...
    def recommend(self, options: List[Dict[str, Any]]) -> Dict[str, Any]: ...


class IOptimizer(Protocol):
    def optimize(self, objective: str, constraints: List[Dict[str, Any]]) -> Dict[str, Any]: ...
    def simulate(self, params: Dict[str, Any]) -> Dict[str, Any]: ...
