"""BI Interfaces — Abstract interfaces for BI components."""
from typing import Any, Protocol


class IDataSource(Protocol):
    def connect(self) -> bool: ...
    def disconnect(self) -> None: ...
    def query(self, sql: str) -> list[dict[str, Any]]: ...
    def get_schema(self) -> dict[str, str]: ...


class IAnalyzer(Protocol):
    def analyze(self, data: list[dict[str, Any]], analysis_type: str) -> dict[str, Any]: ...
    def get_insights(self) -> list[dict[str, Any]]: ...


class IPredictor(Protocol):
    def train(self, data: list[dict[str, Any]], target: str) -> bool: ...
    def predict(self, features: dict[str, Any]) -> float: ...
    def get_accuracy(self) -> float: ...


class IDashboard(Protocol):
    def add_widget(self, widget: dict[str, Any]) -> str: ...
    def remove_widget(self, widget_id: str) -> bool: ...
    def render(self) -> dict[str, Any]: ...


class IReporter(Protocol):
    def generate(self, config: dict[str, Any]) -> str: ...
    def export(self, format: str) -> bytes: ...


class IDecisionEngine(Protocol):
    def evaluate(self, context: dict[str, Any]) -> dict[str, Any]: ...
    def recommend(self, options: list[dict[str, Any]]) -> dict[str, Any]: ...


class IOptimizer(Protocol):
    def optimize(self, objective: str, constraints: list[dict[str, Any]]) -> dict[str, Any]: ...
    def simulate(self, params: dict[str, Any]) -> dict[str, Any]: ...
