from __future__ import annotations

from typing import Any, Protocol


class IDevOpsProvider(Protocol):
    """Protocol for cloud/infrastructure providers."""

    def provision(self, config: dict[str, Any]) -> dict[str, Any]: ...
    def destroy(self, resource_id: str) -> bool: ...
    def status(self, resource_id: str) -> dict[str, Any]: ...
    def list_resources(self) -> list[dict[str, Any]]: ...


class IDeploymentStrategy(Protocol):
    """Protocol for deployment strategies."""

    def deploy(self, service: str, environment: str, config: dict[str, Any]) -> dict[str, Any]: ...
    def rollback(self, deployment_id: str) -> dict[str, Any]: ...
    def validate(self, deployment_id: str) -> bool: ...
