from __future__ import annotations

from typing import Any, Protocol


class IScreen(Protocol):
    """Protocol for renderable screens."""

    def mount(self, container: Any) -> None: ...
    def unmount(self) -> None: ...
    def render(self) -> Any: ...
    def update(self, state: dict[str, Any]) -> None: ...


class IComponent(Protocol):
    """Protocol for UI components."""

    def render(self, props: dict[str, Any]) -> Any: ...
    def attach(self, event: str, handler: Any) -> None: ...
    def destroy(self) -> None: ...
