from __future__ import annotations

from typing import Any, Protocol


class IThemeProvider(Protocol):
    """Protocol for theme providers."""

    def get_colors(self, mode: str) -> dict[str, str]: ...
    def get_typography(self) -> dict[str, Any]: ...
    def get_spacing(self) -> dict[str, int]: ...


class IStateStore(Protocol):
    """Protocol for state stores."""

    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def subscribe(self, key: str, listener: Any) -> None: ...
    def snapshot(self) -> dict[str, Any]: ...
