"""Monitoring protocols."""
from __future__ import annotations
from typing import Any, Dict, Protocol, runtime_checkable

@runtime_checkable
class Loggable(Protocol):
    def to_log_entry(self) -> Dict[str, Any]: ...

@runtime_checkable
class Monitored(Protocol):
    def get_metrics(self) -> Dict[str, float]: ...
    def get_health(self) -> str: ...

@runtime_checkable
class Traceable(Protocol):
    def get_trace_id(self) -> str: ...
    def get_span(self) -> Dict[str, Any]: ...

@runtime_checkable
class Alertable(Protocol):
    def check_alerts(self) -> list: ...
    def get_alert_rules(self) -> list: ...

@runtime_checkable
class Reportable(Protocol):
    def generate_report(self, report_type: str = "") -> Dict[str, Any]: ...
    def export_report(self, format: str = "json") -> str: ...
