"""Digital Twin protocols."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class TwinProtocol(Protocol):
    def get_state(self) -> dict[str, Any]: ...
    def set_state(self, state: dict[str, Any]) -> None: ...
    def reset(self) -> None: ...


@runtime_checkable
class SimulationProtocol(Protocol):
    def step(self) -> dict[str, Any]: ...
    def run(self, steps: int) -> dict[str, Any]: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...


@runtime_checkable
class PredictionProtocol(Protocol):
    def train(self, data: Any) -> None: ...
    def forecast(self, horizon: int) -> dict[str, Any]: ...


@runtime_checkable
class OptimizationProtocol(Protocol):
    def evaluate(self, solution: dict[str, Any]) -> float: ...
    def search(self, iterations: int) -> dict[str, Any]: ...
