"""Digital Twin protocols."""
from __future__ import annotations
from typing import Any, Dict, Protocol, runtime_checkable

@runtime_checkable
class TwinProtocol(Protocol):
    def get_state(self) -> Dict[str, Any]: ...
    def set_state(self, state: Dict[str, Any]) -> None: ...
    def reset(self) -> None: ...

@runtime_checkable
class SimulationProtocol(Protocol):
    def step(self) -> Dict[str, Any]: ...
    def run(self, steps: int) -> Dict[str, Any]: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...

@runtime_checkable
class PredictionProtocol(Protocol):
    def train(self, data: Any) -> None: ...
    def forecast(self, horizon: int) -> Dict[str, Any]: ...

@runtime_checkable
class OptimizationProtocol(Protocol):
    def evaluate(self, solution: Dict[str, Any]) -> float: ...
    def search(self, iterations: int) -> Dict[str, Any]: ...
