"""
Security Interfaces
"""
from typing import Protocol, Optional, Dict, Any, List
from abc import ABC, abstractmethod


class SecurityScanner(Protocol):
    def scan(self, target: Any) -> Dict[str, Any]: ...
    def get_findings(self) -> List[Dict[str, Any]]: ...


class ThreatDetector(Protocol):
    def detect(self, event: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    def get_threats(self) -> List[Dict[str, Any]]: ...


class EncryptionProvider(Protocol):
    def encrypt(self, data: bytes, key: bytes) -> bytes: ...
    def decrypt(self, data: bytes, key: bytes) -> bytes: ...
    def generate_key(self) -> bytes: ...


class AuthenticationProvider(Protocol):
    def authenticate(self, credentials: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    def validate_token(self, token: str) -> bool: ...
    def revoke_token(self, token: str) -> None: ...


class AuthorizationProvider(Protocol):
    def check_permission(self, user_id: str, resource: str, action: str) -> bool: ...
    def get_permissions(self, user_id: str) -> List[str]: ...


class AuditProvider(Protocol):
    def log(self, action: str, user_id: str, resource: str, details: Dict[str, Any]) -> None: ...
    def query(self, filters: Dict[str, Any]) -> List[Dict[str, Any]]: ...
