"""
Security Interfaces
"""

from typing import Any, Protocol


class SecurityScanner(Protocol):
    def scan(self, target: Any) -> dict[str, Any]: ...
    def get_findings(self) -> list[dict[str, Any]]: ...


class ThreatDetector(Protocol):
    def detect(self, event: dict[str, Any]) -> dict[str, Any] | None: ...
    def get_threats(self) -> list[dict[str, Any]]: ...


class EncryptionProvider(Protocol):
    def encrypt(self, data: bytes, key: bytes) -> bytes: ...
    def decrypt(self, data: bytes, key: bytes) -> bytes: ...
    def generate_key(self) -> bytes: ...


class AuthenticationProvider(Protocol):
    def authenticate(self, credentials: dict[str, Any]) -> dict[str, Any] | None: ...
    def validate_token(self, token: str) -> bool: ...
    def revoke_token(self, token: str) -> None: ...


class AuthorizationProvider(Protocol):
    def check_permission(self, user_id: str, resource: str, action: str) -> bool: ...
    def get_permissions(self, user_id: str) -> list[str]: ...


class AuditProvider(Protocol):
    def log(self, action: str, user_id: str, resource: str, details: dict[str, Any]) -> None: ...
    def query(self, filters: dict[str, Any]) -> list[dict[str, Any]]: ...
