"""Skill template — renders a ready-to-edit skill module as source text."""
from __future__ import annotations

_ENTRYPOINT_BODY = (
    'async def __call__(self, script: str = "", **kwargs: Any) -> dict[str, Any]:\n'
    '        """Execute the skill with the merged context/kwargs."""\n'
    "        return {\"skill_id\": self.skill_id, \"echo\": script, **kwargs}"
)


def skill_template(
    *,
    skill_id: str,
    name: str,
    version: str = "1.0.0",
    category: str = "general",
    description: str = "",
    tags: list[str] | None = None,
    permissions: list[str] | None = None,
    entrypoint_body: str | None = None,
) -> str:
    """Return the Python source for a skill module matching the studio pattern."""
    tag_line = ", ".join(f'"{t}"' for t in (tags or []))
    perm_line = ", ".join(f'"{p}"' for p in (permissions or []))
    body = entrypoint_body or _ENTRYPOINT_BODY
    return f'''"""{description} — generated by the SuperDev Skill SDK."""
from __future__ import annotations
from typing import Any


class {name.replace(" ", "")}Skill:
    """{description}"""

    skill_id = "{skill_id}"
    skill_name = "{name}"
    skill_version = "{version}"
    skill_description = "{description}"
    skill_category = "{category}"
    skill_tags = [{tag_line}]
    skill_permissions = [{perm_line}]

    def __init__(self) -> None:
        pass

    {body}
'''
