apiVersion: v1
kind: Namespace
metadata:
  name: superdev
  labels:
    app.kubernetes.io/name: superdev
    app.kubernetes.io/managed-by: argocd
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: superdev-monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: superdev-database
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/managed-by: argocd