"""Narrator profiles — the core general-purpose narrator voices."""
from __future__ import annotations

NARRATOR_PROFILES = [
    {"id": "default", "name": "Default (auto)", "gender": "neutral", "language": "en-US",
     "edge_voice": "en-US-AriaNeural", "gtts_lang": "en", "rate": 1.0, "pitch": 1.0,
     "style": [], "description": "Engine default voice"},
    {"id": "aria", "name": "Aria (en, expressive)", "gender": "female", "language": "en-US",
     "edge_voice": "en-US-AriaNeural", "gtts_lang": "en", "rate": 1.0, "pitch": 1.0,
     "style": ["corporate", "storytelling"], "description": "Warm, expressive US female"},
    {"id": "jenny", "name": "Jenny (en, friendly)", "gender": "female", "language": "en-US",
     "edge_voice": "en-US-JennyNeural", "gtts_lang": "en", "rate": 1.05, "pitch": 1.02,
     "style": ["friendly", "tutorial"], "description": "Friendly, approachable US female"},
    {"id": "guy", "name": "Guy (en, clear)", "gender": "male", "language": "en-US",
     "edge_voice": "en-US-GuyNeural", "gtts_lang": "en", "rate": 1.0, "pitch": 1.0,
     "style": ["narrative", "tech"], "description": "Clear, confident US male"},
    {"id": "sonia", "name": "Sonia (en-GB)", "gender": "female", "language": "en-GB",
     "edge_voice": "en-GB-SoniaNeural", "gtts_lang": "en", "rate": 0.98, "pitch": 1.0,
     "style": ["documentary"], "description": "Calm, authoritative UK female"},
    {"id": "ryan", "name": "Ryan (en-GB)", "gender": "male", "language": "en-GB",
     "edge_voice": "en-GB-RyanNeural", "gtts_lang": "en", "rate": 1.0, "pitch": 1.0,
     "style": ["news", "documentary"], "description": "Newsreader-style UK male"},
    {"id": "francisca", "name": "Francisca (pt-BR)", "gender": "female", "language": "pt-BR",
     "edge_voice": "pt-BR-FranciscaNeural", "gtts_lang": "pt", "rate": 1.0, "pitch": 1.0,
     "style": ["corporate", "friendly"], "description": "Natural Brazilian Portuguese female"},
    {"id": "antonio", "name": "Antonio (pt-BR)", "gender": "male", "language": "pt-BR",
     "edge_voice": "pt-BR-AntonioNeural", "gtts_lang": "pt", "rate": 0.98, "pitch": 0.98,
     "style": ["narrative", "corporate"], "description": "Deep Brazilian Portuguese male"},
    {"id": "yuki", "name": "Yuki (ja)", "gender": "female", "language": "ja-JP",
     "edge_voice": "ja-JP-NanamiNeural", "gtts_lang": "ja", "rate": 1.02, "pitch": 1.03,
     "style": ["anime", "friendly"], "description": "Soft Japanese female"},
    {"id": "elena", "name": "Elena (es)", "gender": "female", "language": "es-ES",
     "edge_voice": "es-ES-ElviraNeural", "gtts_lang": "es", "rate": 1.0, "pitch": 1.0,
     "style": ["corporate", "storytelling"], "description": "Melodic Spanish female"},
]
