export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "/api/v1";

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    ME: "/auth/me",
    VERIFY_EMAIL: "/auth/verify-email",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
  },
  USERS: {
    BASE: "/users",
    PROFILE: (id: string) => `/users/${id}`,
    PREFERENCES: "/users/preferences",
    UPDATE_PASSWORD: "/users/password",
  },
  PROJECTS: {
    BASE: "/projects",
    DETAIL: (id: string) => `/projects/${id}`,
    MEMBERS: (id: string) => `/projects/${id}/members`,
    STATS: (id: string) => `/projects/${id}/stats`,
  },
  HEALTH: {
    CHECK: "/health",
    READY: "/health/ready",
    LIVE: "/health/live",
  },
  WORKSPACE: {
    BASE: "/workspace",
    SESSIONS: "/workspace/sessions",
    SESSION: (id: string) => `/workspace/sessions/${id}`,
  },
  LLM: {
    PROVIDERS: "/llm/providers",
    PROVIDER_DETAIL: (name: string) => `/llm/providers/${name}`,
    PROVIDER_TEST: (name: string) => `/llm/providers/${name}/test`,
    MODELS: "/llm/models",
    CHAT: "/llm/chat",
    CHAT_STREAM: "/llm/chat/stream",
    HEALTH: "/llm/health",
  },
  DASHBOARD: {
    BASE: "/system/dashboard",
  },
  AGENTS: {
    BASE: "/agents",
  },
  WORKFLOWS: {
    BASE: "/workflows",
  },
  ARCHITECTURE_GRAPH: {
    BASE: "/architecture-graph",
    HEALTH: "/architecture-graph/health",
    STATS: "/architecture-graph/stats",
    ANALYZE: "/architecture-graph/analyze",
    INSIGHTS: "/architecture-graph/insights",
    RISK: "/architecture-graph/insights/risk",
    SEARCH: "/architecture-graph/search",
    EXPORT: (fmt: string) => `/architecture-graph/export/${fmt}`,
    REPORTS: (kind: string) => `/architecture-graph/reports/${kind}`,
  },
  ARCHITECTURE_INTELLIGENCE: {
    BASE: "/architecture-intelligence",
    METRICS: "/architecture-intelligence/metrics",
    INSIGHTS: "/architecture-intelligence/insights",
    PLAN: "/architecture-intelligence/plan",
    FORECAST: "/architecture-intelligence/forecast",
    TRENDS: "/architecture-intelligence/trends",
    OPTIMIZE: "/architecture-intelligence/optimize",
    DIAGNOSE: "/architecture-intelligence/diagnose",
    AGENTS: "/architecture-intelligence/agents",
    HISTORY: "/architecture-intelligence/history",
    SNAPSHOT: "/architecture-intelligence/snapshot",
    ASK: "/architecture-intelligence/ask",
    REPORT: "/architecture-intelligence/report",
  },
  EVOLUTION: {
    BASE: "/evolution",
    STATUS: "/evolution/status",
    ANALYZE: "/evolution/analyze",
    RECOMMEND: "/evolution/recommend",
    APPROVE: "/evolution/approve",
    REJECT: "/evolution/reject",
    START: "/evolution/start",
    STOP: "/evolution/stop",
    INTEGRATIONS: "/evolution/integrations",
    DASHBOARD: "/evolution/dashboard",
  },
  DIGITAL_TWIN: {
    BASE: "/digital-twin",
    STATUS: "/digital-twin/status",
    ENDPOINTS: "/digital-twin/endpoints",
    CONFIG: "/digital-twin/config",
    START: "/digital-twin/start",
    STOP: "/digital-twin/stop",
    CYCLE: "/digital-twin/cycle",
    TICK: "/digital-twin/tick",
    BUILD_TWIN: "/digital-twin/build-twin",
    SNAPSHOT: "/digital-twin/snapshot",
    ANALYZE: "/digital-twin/analyze",
    VALIDATE: "/digital-twin/validate",
  },
  SELF_HEALING: {
    BASE: "/self-healing",
    STATUS: "/self-healing/status",
    RUN: "/self-healing/run",
    EVENTS: "/self-healing/events",
  },
  AUTONOMOUS_DEVELOPER: {
    BASE: "/autonomous-developer",
    STATUS: "/autonomous-developer/status",
    EXECUTE: "/autonomous-developer/execute",
    RESET: "/autonomous-developer/reset",
    SESSIONS: "/autonomous-developer/sessions",
  },
  KNOWLEDGE_GRAPH: {
    BASE: "/knowledge-graph",
    SCAN: "/knowledge-graph/scan",
    STATUS: "/knowledge-graph/status",
    SNAPSHOT: "/knowledge-graph/snapshot",
    FILES: "/knowledge-graph/files",
    ENTITY_COUNTS: "/knowledge-graph/entity-counts",
    LANGUAGES: "/knowledge-graph/languages",
    RESET: "/knowledge-graph/reset",
  },
  ORCHESTRATOR: {
    BASE: "/orchestrator",
    STATUS: "/orchestrator/status",
    CONFIG: "/orchestrator/config",
    GOVERNANCE: "/orchestrator/governance",
    TASKS: "/orchestrator/tasks",
    TASK: (seq: number) => `/orchestrator/tasks/${seq}`,
    APPROVE: (seq: number) => `/orchestrator/tasks/${seq}/approve`,
    REJECT: (seq: number) => `/orchestrator/tasks/${seq}/reject`,
    CANCEL: (seq: number) => `/orchestrator/tasks/${seq}/cancel`,
    PAUSE: (seq: number) => `/orchestrator/tasks/${seq}/pause`,
    RESUME: (seq: number) => `/orchestrator/tasks/${seq}/resume`,
    ROLLBACK: (seq: number) => `/orchestrator/tasks/${seq}/rollback`,
    TICK: "/orchestrator/tick",
    HEALTH: "/orchestrator/health",
    METRICS: "/orchestrator/metrics",
    ANALYTICS: "/orchestrator/analytics",
    AUDIT: "/orchestrator/audit",
    EVENTS: "/orchestrator/events",
    MEMORY: "/orchestrator/memory",
    MEMORY_NS: (ns: string) => `/orchestrator/memory/${ns}`,
    INTEGRATIONS: "/orchestrator/integrations",
    INTEGRATION_INVOKE: (name: string) => `/orchestrator/integrations/${name}/invoke`,
    DASHBOARD: "/orchestrator/dashboard",
  },
  SYSTEM: {
    BASE: "/system",
    STATUS: "/system/status",
    HEALTH: "/system/health",
    SELF_TEST: "/system/self-test",
    BOOT: "/system/boot",
    SHUTDOWN: "/system/shutdown",
    AGENTS: "/system/agents",
    AGENT_START: (id: string) => `/system/agents/${id}/start`,
    AGENT_STOP: (id: string) => `/system/agents/${id}/stop`,
    AGENT_EXECUTE: "/system/agents/execute",
    SCHEDULER_TASKS: "/system/scheduler/tasks",
    SCHEDULER_RUN: (id: string) => `/system/scheduler/run/${id}`,
    METRICS: "/system/metrics",
  },
  AI: {
    BASE: "/ai",
    HEALTH: "/ai/health",
    MODULES: "/ai/modules",
    STATS: "/ai/stats",
    CYBERSECURITY_STATS: "/ai/cybersecurity/stats",
    THREATS: "/ai/cybersecurity/threats",
    DATA_PLATFORM_STATS: "/ai/data-platform/stats",
    ERP_STATS: "/ai/erp/stats",
    KNOWLEDGE_STATS: "/ai/knowledge/stats",
  },
  BACKUP: {
    BASE: "/backup",
    DATABASE: "/backup/database",
    FILES: "/backup/files",
    FULL: "/backup/full",
    RESTORE: "/backup/restore",
    STATS: "/backup/stats",
  },
  EMAIL: {
    BASE: "/email",
    TEMPLATES: "/email/templates",
    SEND: "/email/send",
    STATS: "/email/stats",
  },
  COST: {
    BASE: "/cost",
    SUMMARY: "/cost/summary",
    BREAKDOWN: "/cost/breakdown",
    USAGE: "/cost/usage",
    FORECAST: "/cost/forecast",
  },
  PLUGINS: {
    BASE: "/plugins",
    REGISTRY: "/plugins/registry",
    POPULAR: "/plugins/registry/popular",
    CATEGORIES: "/plugins/registry/categories",
    INSTALLED: "/plugins/installed",
    INSTALL: "/plugins/install",
    ENABLE: (slug: string) => `/plugins/${slug}/enable`,
    DISABLE: (slug: string) => `/plugins/${slug}/disable`,
    UNINSTALL: (slug: string) => `/plugins/${slug}`,
    CONFIG: (slug: string) => `/plugins/${slug}/config`,
  },
  SCANNERS: {
    BASE: "/scanners",
    SCAN_ALL: "/scanners/all/scan",
    SCAN: (id: string) => `/scanners/${id}/scan`,
  },
  BUILDERS: {
    BASE: "/builders",
    BUILD_ALL: "/builders/all/build",
    BUILD: (id: string) => `/builders/${id}/build`,
  },
  HARNESS: {
    BASE: "/harness",
    STATUS: "/harness/status",
    DOMAINS: "/harness/domains",
    AGENTS: "/harness/agents",
    SKILLS: "/harness/skills",
    SKILL: (id: string) => `/harness/skills/${id}`,
    EXECUTE: "/harness/execute",
  },
  FEATURE_FLAGS: {
    BASE: "/feature-flags",
    FLAG: (name: string) => `/feature-flags/${name}`,
    TOGGLE: (name: string) => `/feature-flags/${name}/toggle`,
    CHECK: (name: string) => `/feature-flags/check/${name}`,
  },
  KNOWLEDGE: {
    BASE: "/knowledge",
    KNOWLEDGE_BASES: "/knowledge/knowledge-bases",
    KNOWLEDGE_BASE: (id: string) => `/knowledge/knowledge-bases/${id}`,
    DOCUMENTS: (id: string) => `/knowledge/knowledge-bases/${id}/documents`,
    SEARCH: "/knowledge/knowledge-bases/search",
    SEARCH_IN: (id: string) => `/knowledge/knowledge-bases/${id}/search`,
    CONTEXT: "/knowledge/knowledge-bases/context",
    CONTEXT_IN: (id: string) => `/knowledge/knowledge-bases/${id}/context`,
    INGEST_REPO: (id: string) => `/knowledge/knowledge-bases/${id}/ingest-repo`,
    SIMILAR_CODE: (id: string) => `/knowledge/knowledge-bases/${id}/similar-code`,
  },
  DATA: {
    BASE: "/data",
    EXPORT: "/data/export",
    EXPORTS: "/data/exports",
    IMPORTS: "/data/imports",
    IMPORT_JSON: "/data/import/json",
    IMPORT_CSV: "/data/import/csv",
  },
  VERIFICATION: {
    BASE: "/verification",
    VERIFY: "/verification/verify",
    GENERATE: "/verification/generate",
    EXECUTE: "/verification/execute",
    REVIEW: "/verification/review",
  },
  NOTIFICATIONS: {
    BASE: "/notifications",
    UNREAD_COUNT: "/notifications/unread-count",
    READ: (id: string) => `/notifications/${id}/read`,
    READ_ALL: "/notifications/read-all",
    NOTIFICATION: (id: string) => `/notifications/${id}`,
  },
  EXECUTIONS: {
    BASE: "/executions",
    STATS_TODAY: "/executions/stats/today",
  },
  SEARCH: {
    BASE: "/search",
    INDEX: "/search/index",
    SEARCH: "/search/search",
    DOCUMENTS: "/search/documents",
    DOCUMENT: (id: string) => `/search/documents/${id}`,
    STATS: "/search/stats",
  },
  API_KEYS: {
    BASE: "/api-keys",
    KEY: (id: string) => `/api-keys/${id}`,
  },
  I18N: {
    BASE: "/i18n",
    LOCALES: "/i18n/locales",
    STATS: "/i18n/stats",
    TRANSLATE: "/i18n/translate",
  },
} as const;

export const API_TIMEOUT = 30000;
export const AGENT_TIMEOUT = 300000; // 5 minutes for agent tasks
export const API_RETRY_COUNT = 3;
export const API_RETRY_DELAY = 1000;
