---
- name: Configurar backend
  block:
    - name: Criar diretório de aplicação
      file:
        path: /opt/superdev/backend
        state: directory
        owner: superdev

    - name: Copiar docker-compose
      template:
        src: docker-compose.yml.j2
        dest: /opt/superdev/docker-compose.yml

    - name: Iniciar serviços
      docker_compose:
        project_src: /opt/superdev
        state: present
