"""Data models for code generation."""

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


class TemplateLanguage(Enum):
    PYTHON = "python"
    TYPESCRIPT = "typescript"
    JAVA = "java"
    GO = "go"
    RUST = "rust"
    KOTLIN = "kotlin"
    SWIFT = "swift"


@dataclass
class GeneratedFile:
    """A file generated by the system."""

    file_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    path: str = ""
    content: str = ""
    language: TemplateLanguage = TemplateLanguage.PYTHON
    template_used: str = ""
    variables: dict[str, Any] = field(default_factory=dict)
    generated_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class TemplateVariable:
    """A variable in a template."""

    name: str = ""
    type: str = "string"
    default_value: Any = ""
    required: bool = True
    description: str = ""


@dataclass
class Template:
    """A code generation template."""

    template_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    name: str = ""
    content: str = ""
    language: TemplateLanguage = TemplateLanguage.PYTHON
    variables: list[TemplateVariable] = field(default_factory=list)
    description: str = ""

    def render(self, variables: dict[str, Any]) -> str:
        result = self.content
        for var in self.variables:
            placeholder = f"{{{{{var.name}}}}}"
            value = variables.get(var.name, var.default_value)
            result = result.replace(placeholder, str(value))
        for key, value in variables.items():
            placeholder = f"{{{{{key}}}}}"
            result = result.replace(placeholder, str(value))
        return result


@dataclass
class GenerationProject:
    """A code generation project configuration."""

    project_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    name: str = ""
    output_dir: str = ""
    templates: list[str] = field(default_factory=list)
    global_variables: dict[str, Any] = field(default_factory=dict)
    language: TemplateLanguage = TemplateLanguage.PYTHON


@dataclass
class ScaffoldConfig:
    """Configuration for project scaffolding."""

    project_name: str = ""
    project_type: str = "library"
    language: TemplateLanguage = TemplateLanguage.PYTHON
    features: list[str] = field(default_factory=list)
    structure: dict[str, Any] = field(default_factory=dict)


@dataclass
class TransformRule:
    """A code transformation rule."""

    rule_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    name: str = ""
    pattern: str = ""
    replacement: str = ""
    language: TemplateLanguage = TemplateLanguage.PYTHON
    enabled: bool = True
