"""Base classes and types for the SuperDev builder system.

Builders generate project scaffolding, code templates, and microservices
for various frameworks and platforms.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


class FrameworkType(str, Enum):
    """Supported framework types for code generation."""
    FASTAPI = "fastapi"
    DJANGO = "django"
    FLASK = "flask"
    REACT = "react"
    NEXTJS = "nextjs"
    VUE = "vue"
    SVELTE = "svelte"
    EXPRESS = "express"
    NESTJS = "nestjs"
    FLUTTER = "flutter"
    ELECTRON = "electron"
    NODE = "node"
    PYTHON = "python"


class DatabaseType(str, Enum):
    POSTGRESQL = "postgresql"
    MYSQL = "mysql"
    SQLITE = "sqlite"
    MONGODB = "mongodb"
    REDIS = "redis"


class ApiType(str, Enum):
    REST = "rest"
    GRAPHQL = "graphql"
    WEBSOCKET = "websocket"
    GRPC = "grpc"


@dataclass
class GeneratedFile:
    """Represents a single file generated by a builder."""
    path: str
    content: str
    language: str = ""
    overwrite: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "path": self.path,
            "content_length": len(self.content),
            "language": self.language,
            "overwrite": self.overwrite,
        }


@dataclass
class BuildConfig:
    """Configuration for a build/generation request."""
    project_name: str = "my-app"
    project_slug: str = ""
    output_dir: str = "."
    framework: FrameworkType = FrameworkType.FASTAPI
    database: DatabaseType = DatabaseType.POSTGRESQL
    api_type: ApiType = ApiType.REST
    include_auth: bool = True
    include_docker: bool = True
    include_tests: bool = True
    include_ci: bool = False
    include_docs: bool = False
    packages: list[str] = field(default_factory=list)
    extra_config: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.project_slug:
            self.project_slug = self.project_name.lower().replace(" ", "-").replace("_", "-")


@dataclass
class BuildResult:
    """Result of a build/generation operation."""
    builder_name: str
    project_name: str = ""
    project_slug: str = ""
    total_files: int = 0
    files: list[GeneratedFile] = field(default_factory=list)
    build_duration_ms: float = 0.0
    error: str = ""
    timestamp: str = ""

    @property
    def has_errors(self) -> bool:
        return bool(self.error)

    def to_dict(self) -> dict[str, Any]:
        return {
            "builder_name": self.builder_name,
            "project_name": self.project_name,
            "project_slug": self.project_slug,
            "total_files": self.total_files,
            "files": [f.to_dict() for f in self.files],
            "build_duration_ms": self.build_duration_ms,
            "error": self.error,
            "timestamp": self.timestamp or datetime.now(timezone.utc).isoformat(),
        }


class BaseBuilder:
    """Abstract base class for all builders.

    Builders generate project scaffolding, code templates, and configuration
    files for specific frameworks and platforms.
    """

    name: str = "base"
    description: str = ""
    framework: FrameworkType = FrameworkType.PYTHON

    async def build(self, config: BuildConfig) -> BuildResult:
        """Generate project files based on the given configuration."""
        raise NotImplementedError(
            f"{self.__class__.__name__} must implement build()"
        )

    def _make_file(self, path: str, content: str, language: str = "", overwrite: bool = False) -> GeneratedFile:
        return GeneratedFile(
            path=path,
            content=content,
            language=language or self._detect_language(path),
            overwrite=overwrite,
        )

    def _detect_language(self, path: str) -> str:
        ext_map = {
            ".py": "python", ".js": "javascript", ".ts": "typescript",
            ".tsx": "typescript", ".jsx": "javascript", ".json": "json",
            ".yaml": "yaml", ".yml": "yaml", ".md": "markdown",
            ".html": "html", ".css": "css", ".dockerfile": "dockerfile",
            ".sh": "shell", ".toml": "toml", ".cfg": "ini",
        }
        import os
        return ext_map.get(os.path.splitext(path)[1].lower(), "")

    def _write_files(self, base_dir: str, files: list[GeneratedFile]) -> int:
        """Write generated files to disk. Returns count of written files."""
        import os
        written = 0
        for f in files:
            full_path = os.path.join(base_dir, f.path)
            os.makedirs(os.path.dirname(full_path), exist_ok=True)
            if os.path.exists(full_path) and not f.overwrite:
                continue
            with open(full_path, "w", encoding="utf-8") as fh:
                fh.write(f.content)
            written += 1
        return written
