"""Enterprise interfaces."""
from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional

class OrganizationInterface(ABC):
    @abstractmethod
    def create(self, name: str, slug: str) -> Dict[str, Any]: ...
    @abstractmethod
    def get(self, org_id: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    def update(self, org_id: str, **kwargs: Any) -> Dict[str, Any]: ...
    @abstractmethod
    def delete(self, org_id: str) -> bool: ...
    @abstractmethod
    def list_all(self) -> List[Dict[str, Any]]: ...

class BillingInterface(ABC):
    @abstractmethod
    def calculate(self, org_id: str, items: List[Dict[str, Any]]) -> Dict[str, Any]: ...
    @abstractmethod
    def charge(self, org_id: str, amount: float) -> Dict[str, Any]: ...
    @abstractmethod
    def get_history(self, org_id: str) -> List[Dict[str, Any]]: ...

class LicenseInterface(ABC):
    @abstractmethod
    def generate(self, org_id: str, plan_id: str) -> Dict[str, Any]: ...
    @abstractmethod
    def validate(self, key: str) -> bool: ...
    @abstractmethod
    def activate(self, key: str) -> bool: ...
    @abstractmethod
    def revoke(self, key: str) -> bool: ...

class UsageInterface(ABC):
    @abstractmethod
    def track(self, org_id: str, metric: str, quantity: float) -> bool: ...
    @abstractmethod
    def get_usage(self, org_id: str, metric: str = "") -> Dict[str, Any]: ...
    @abstractmethod
    def get_quota(self, org_id: str) -> Dict[str, Any]: ...

class SubscriptionInterface(ABC):
    @abstractmethod
    def create(self, org_id: str, plan_id: str) -> Dict[str, Any]: ...
    @abstractmethod
    def cancel(self, subscription_id: str) -> bool: ...
    @abstractmethod
    def upgrade(self, subscription_id: str, new_plan: str) -> Dict[str, Any]: ...
