"""Enterprise interfaces."""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any


class OrganizationInterface(ABC):
    @abstractmethod
    def create(self, name: str, slug: str) -> dict[str, Any]: ...
    @abstractmethod
    def get(self, org_id: str) -> dict[str, Any] | None: ...
    @abstractmethod
    def update(self, org_id: str, **kwargs: Any) -> dict[str, Any]: ...
    @abstractmethod
    def delete(self, org_id: str) -> bool: ...
    @abstractmethod
    def list_all(self) -> list[dict[str, Any]]: ...

class BillingInterface(ABC):
    @abstractmethod
    def calculate(self, org_id: str, items: list[dict[str, Any]]) -> dict[str, Any]: ...
    @abstractmethod
    def charge(self, org_id: str, amount: float) -> dict[str, Any]: ...
    @abstractmethod
    def get_history(self, org_id: str) -> list[dict[str, Any]]: ...

class LicenseInterface(ABC):
    @abstractmethod
    def generate(self, org_id: str, plan_id: str) -> dict[str, Any]: ...
    @abstractmethod
    def validate(self, key: str) -> bool: ...
    @abstractmethod
    def activate(self, key: str) -> bool: ...
    @abstractmethod
    def revoke(self, key: str) -> bool: ...

class UsageInterface(ABC):
    @abstractmethod
    def track(self, org_id: str, metric: str, quantity: float) -> bool: ...
    @abstractmethod
    def get_usage(self, org_id: str, metric: str = "") -> dict[str, Any]: ...
    @abstractmethod
    def get_quota(self, org_id: str) -> dict[str, Any]: ...

class SubscriptionInterface(ABC):
    @abstractmethod
    def create(self, org_id: str, plan_id: str) -> dict[str, Any]: ...
    @abstractmethod
    def cancel(self, subscription_id: str) -> bool: ...
    @abstractmethod
    def upgrade(self, subscription_id: str, new_plan: str) -> dict[str, Any]: ...
