[production]
prod-superdev-1 ansible_host=123.123.123.1 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/production.pem
prod-superdev-2 ansible_host=123.123.123.2 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/production.pem

[staging]
staging-superdev ansible_host=123.123.123.10 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/staging.pem

[development]
dev-superdev ansible_host=123.123.123.20 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/development.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'