"""DevOps protocols."""
from __future__ import annotations
from typing import Any, Dict, Protocol, runtime_checkable

@runtime_checkable
class DevOpsProtocol(Protocol):
    def configure(self, config: Dict[str, Any]) -> None: ...
    def execute(self, command: str) -> Dict[str, Any]: ...

@runtime_checkable
class InfrastructureProtocol(Protocol):
    def create_resource(self, config: Dict[str, Any]) -> Dict[str, Any]: ...
    def delete_resource(self, resource_id: str) -> bool: ...
    def list_resources(self) -> List[Dict[str, Any]]: ...

@runtime_checkable
class MonitoringProtocol(Protocol):
    def collect_metrics(self) -> Dict[str, Any]: ...
    def check_health(self) -> Dict[str, Any]: ...
    def alert(self, condition: str, severity: str) -> None: ...
