"""DevOps interfaces."""
from __future__ import annotations
from typing import Any, Dict, Protocol, runtime_checkable

@runtime_checkable
class Provisionable(Protocol):
    def provision(self, config: Dict[str, Any]) -> Dict[str, Any]: ...
    def deprovision(self, resource_id: str) -> bool: ...

@runtime_checkable
class Deployable(Protocol):
    def deploy(self, config: Dict[str, Any]) -> Dict[str, Any]: ...
    def rollback(self, deployment_id: str) -> bool: ...

@runtime_checkable
class Scalable(Protocol):
    def scale_up(self, amount: int) -> Dict[str, Any]: ...
    def scale_down(self, amount: int) -> Dict[str, Any]: ...

@runtime_checkable
class Monitorable(Protocol):
    def get_status(self) -> Dict[str, Any]: ...
    def get_metrics(self) -> Dict[str, Any]: ...
