"""Configuration package for the AI Evolution Engine."""
from __future__ import annotations

from modules.ai_evolution_engine.config.constants import (
    ALL_PHASES,
    DECISION_APPROVED,
    DECISION_ESCALATED,
    DECISION_PENDING,
    DECISION_REJECTED,
    EVENT_ANALYSIS_COMPLETED,
    EVENT_FORECAST_CREATED,
    EVENT_GOVERNANCE_DECIDED,
    EVENT_RECOMMENDATION_APPROVED,
    EVENT_RECOMMENDATION_CREATED,
    EVENT_RECOMMENDATION_REJECTED,
    EVENT_ROADMAP_PLANNED,
    EVENT_TICK,
    HORIZON_LONG,
    HORIZON_MEDIUM,
    HORIZON_SHORT,
    ITEM_BACKLOG,
    ITEM_DONE,
    ITEM_DROPPED,
    ITEM_IN_PROGRESS,
    ITEM_PLANNED,
    PHASE_ANALYZE,
    PHASE_FORECAST,
    PHASE_GOVERN,
    PHASE_LEARN,
    PHASE_PLAN,
    PHASE_RECOMMEND,
    PHASE_REPORT,
    REC_APPROVED,
    REC_API,
    REC_ARCHITECTURE,
    REC_DATABASE,
    REC_DEPENDENCY,
    REC_DRAFT,
    REC_IMPLEMENTED,
    REC_MODERNIZATION,
    REC_PENDING,
    REC_PERFORMANCE,
    REC_PLUGIN,
    REC_REJECTED,
    REC_SECURITY,
    REC_SUPERSEDED,
    REC_WORKFLOW,
    SCOPE_FILE,
    SCOPE_MODULE,
    SCOPE_PACKAGE,
    SCOPE_PLATFORM,
    SEVERITY_CRITICAL,
    SEVERITY_INFO,
    SEVERITY_MAJOR,
    SEVERITY_MINOR,
)
from modules.ai_evolution_engine.config.evolution_config import EvolutionConfig
from modules.ai_evolution_engine.config.forecast_config import ForecastConfig
from modules.ai_evolution_engine.config.governance_config import GovernanceConfig
from modules.ai_evolution_engine.config.learning_config import LearningConfig
from modules.ai_evolution_engine.config.optimization_config import (
    OptimizationConfig,
)
from modules.ai_evolution_engine.config.permissions import Permissions
from modules.ai_evolution_engine.config.recommendation_config import (
    RecommendationConfig,
)

__all__ = [
    "ALL_PHASES",
    "DECISION_APPROVED",
    "DECISION_ESCALATED",
    "DECISION_PENDING",
    "DECISION_REJECTED",
    "EVENT_ANALYSIS_COMPLETED",
    "EVENT_FORECAST_CREATED",
    "EVENT_GOVERNANCE_DECIDED",
    "EVENT_RECOMMENDATION_APPROVED",
    "EVENT_RECOMMENDATION_CREATED",
    "EVENT_RECOMMENDATION_REJECTED",
    "EVENT_ROADMAP_PLANNED",
    "EVENT_TICK",
    "EvolutionConfig",
    "ForecastConfig",
    "GovernanceConfig",
    "HORIZON_LONG",
    "HORIZON_MEDIUM",
    "HORIZON_SHORT",
    "ITEM_BACKLOG",
    "ITEM_DONE",
    "ITEM_DROPPED",
    "ITEM_IN_PROGRESS",
    "ITEM_PLANNED",
    "LearningConfig",
    "OptimizationConfig",
    "Permissions",
    "PHASE_ANALYZE",
    "PHASE_FORECAST",
    "PHASE_GOVERN",
    "PHASE_LEARN",
    "PHASE_PLAN",
    "PHASE_RECOMMEND",
    "PHASE_REPORT",
    "REC_APPROVED",
    "REC_API",
    "REC_ARCHITECTURE",
    "REC_DATABASE",
    "REC_DEPENDENCY",
    "REC_DRAFT",
    "REC_IMPLEMENTED",
    "REC_MODERNIZATION",
    "REC_PENDING",
    "REC_PERFORMANCE",
    "REC_PLUGIN",
    "REC_REJECTED",
    "REC_SECURITY",
    "REC_SUPERSEDED",
    "REC_WORKFLOW",
    "RecommendationConfig",
    "SCOPE_FILE",
    "SCOPE_MODULE",
    "SCOPE_PACKAGE",
    "SCOPE_PLATFORM",
    "SEVERITY_CRITICAL",
    "SEVERITY_INFO",
    "SEVERITY_MAJOR",
    "SEVERITY_MINOR",
]
