from __future__ import annotations

import logging
from typing import Any

from .editor_engine import EditorEngine


class AICodeAssistant:
    """AI assistant features bound to the editor."""

    def __init__(self, engine: EditorEngine) -> None:
        self._log = logging.getLogger("superdev.frontend.editor.ai")
        self._engine = engine
        self._history: list[dict[str, Any]] = []

    def inline_complete(self, path: str, prefix: str) -> dict[str, Any]:
        suggestion = self._engine.suggest(path, prefix)
        completion = suggestion[0] if suggestion else None
        result = {"path": path, "completion": completion, "accepted": False}
        self._history.append(result)
        return result

    def explain(self, code: str) -> dict[str, Any]:
        return {
            "language": "python",
            "summary": "Code explanation generated by the AI assistant engine.",
            "lines": len(code.splitlines()),
        }

    def refactor(self, path: str, operation: str, **params: Any) -> dict[str, Any]:
        return {"path": path, "operation": operation, "params": params, "status": "planned"}

    def history(self, limit: int | None = None) -> list[dict[str, Any]]:
        events = list(self._history)
        if limit is not None:
            events = events[-limit:]
        return events
